#spring.kafka.bootstrap-servers= kafka-dev-supply-chain-01.xxxxx.cn:9092
#spring.kafka.properties.security.protocol = SASL_PLAINTEXT
#spring.kafka.properties.sasl.mechanism = SCRAM-SHA-256
#spring.kafka.properties.sasl.jaas.config = org.apache.kafka.common.security.scram.ScramLoginModule required username="xxxx" password="xxxx";
#
#spring.kafka.producer.key-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.batch-size=65536
#spring.kafka.producer.buffer-memory=524288
#
## consumer config
#spring.kafka.consumer.group-id=kafka-gray-test-group
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer









