context.mvc.log.enable=false
spring.application.name=official-site
logging.level.root=info
logging.level.com.pj.official=info
server.port=8089
spring.http.encoding.charset=utf-8
management.security.enabled=false
swagger.basePackage=com.dbcat
spring.jackson.date-format=yy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
mybatis.mapper-locations=classpath*:mappers/*Mapper.xml
mybatis.configuration.map-underscore-to-camel-case=true
#∂©‘ƒ◊¥Ã¨ «∑Ò∆Ù”√
gray.subscript.enable=false




