gateway.verifyOpen=true
spring.datasource.official.jdbc-url=jdbc:mysql://localhost/gray_admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
spring.datasource.official.username=root
spring.datasource.official.password=root
spring.datasource.official.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.official.initialSize=5
spring.datasource.official.maxActive=20
spring.datasource.official.maxIdle=5
spring.datasource.official.minIdle=2







